package com.ties.storage.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.UUID;

/**
 * BlockEntity — JPA Entity
 *
 * Maps directly to the capture_blocks table in PostgreSQL.
 * This is the persistence model for block metadata —
 * separate from the CaptureBlock model which is the
 * Kafka message model.
 *
 * Why two separate classes?
 * - CaptureBlock is the incoming Kafka message shape
 * - BlockEntity is the PostgreSQL storage shape
 * - They are intentionally different — the database schema
 *   may evolve independently from the message contract
 * - Keeping them separate avoids coupling transport
 *   layer to persistence layer (clean architecture)
 *
 * Maps to init.sql table:
 * capture_blocks (
 *   id, block_identifier, session_id, device_id,
 *   captured_at, frame_count, quality_score,
 *   spatial_label, transmission_status,
 *   received_at, checksum
 * )
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "capture_blocks")
public class BlockEntity {

    /**
     * Primary key — UUID auto-generated by PostgreSQL.
     * Matches gen_random_uuid() in init.sql.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * Unique identifier from the acquisition device.
     * Format: DEVICE_ID-TIMESTAMP-SEQUENCE
     * Unique constraint matches init.sql UNIQUE NOT NULL.
     */
    @Column(name = "block_identifier", unique = true, nullable = false)
    private String blockIdentifier;

    /**
     * Foreign key reference to mission_sessions table.
     * Stored as UUID string — resolved at query time.
     */
    @Column(name = "session_id")
    private UUID sessionId;

    /**
     * Foreign key reference to devices table.
     * Stored as UUID string — resolved at query time.
     */
    @Column(name = "device_id")
    private UUID deviceId;

    /**
     * Timestamp of first frame capture in this block.
     * Maps to captured_at column in capture_blocks table.
     */
    @Column(name = "captured_at", nullable = false)
    private Instant capturedAt;

    /**
     * Total number of frames in this block.
     * Expected range: 8 to 10.
     * Already validated by validation-service.
     */
    @Column(name = "frame_count", nullable = false)
    private Integer frameCount;

    /**
     * Quality confidence score from acquisition device.
     * Range: 0.0 to 1.0
     * Already pre-filtered above 0.5 by ingestion-service.
     */
    @Column(name = "quality_score")
    private Double qualityScore;

    /**
     * Human readable spatial label from mobile app.
     * Example: "North corridor", "Room 3B"
     */
    @Column(name = "spatial_label")
    private String spatialLabel;

    /**
     * Current transmission status of this block.
     * Set to ACKNOWLEDGED after successful storage.
     * Values: PENDING, TRANSMITTING, ACKNOWLEDGED, FAILED
     */
    @Column(name = "transmission_status")
    private String transmissionStatus;

    /**
     * Timestamp when storage-service received this block.
     * Set at write time — used for pipeline timing analysis.
     */
    @Column(name = "received_at")
    private Instant receivedAt;

    /**
     * SHA-256 checksum of the block payload.
     * Already verified by validation-service.
     * Stored for audit trail purposes.
     */
    @Column(name = "checksum")
    private String checksum;
}