package com.ties.storage.model;

import com.fasterxml.jackson.databind.JsonNode;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.time.Instant;

/**
 * FrameDocument — MongoDB Document Model
 *
 * Represents a single frame stored in MongoDB.
 * Each CaptureBlock produces one FrameDocument per frame
 * into the mapping_images database.
 *
 * Why MongoDB for frames?
 * - Frames contain flexible sensor data (JsonNode fields)
 *   that varies across device types
 * - MongoDB's schema-flexible BSON storage handles this
 *   naturally without migration overhead
 * - Frame binary data (future: actual image bytes) fits
 *   MongoDB's document model better than PostgreSQL columns
 * - High write throughput — 8-10 frames per block per device
 *   benefits from MongoDB's write performance
 *
 * Design decisions:
 * - blockIdentifier and deviceIdentifier are indexed for
 *   fast lookups when retrieving all frames for a block
 * - @Document maps this class to the frames collection
 *   in the mapping_images MongoDB database
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "frames")
public class FrameDocument {

    /**
     * MongoDB document identifier.
     * Auto-generated by MongoDB as an ObjectId.
     * Annotated with @Id to mark it as the primary key.
     */
    @Id
    private String id;

    /**
     * Identifier of the CaptureBlock this frame belongs to.
     * Indexed for fast retrieval of all frames in a block.
     * Format: DEVICE_ID-TIMESTAMP-SEQUENCE
     */
    @Indexed
    @Field("block_identifier")
    private String blockIdentifier;

    /**
     * Identifier of the device that captured this frame.
     * Indexed for fast retrieval of all frames from a device.
     */
    @Indexed
    @Field("device_identifier")
    private String deviceIdentifier;

    /**
     * Identifier of the mission session.
     * Links this frame back to a complete mapping session.
     */
    @Field("session_identifier")
    private String sessionIdentifier;

    /**
     * Position of this frame within its parent CaptureBlock.
     * Zero-indexed. Used to reconstruct frame order during
     * AI processing in the analytical tier.
     */
    @Field("frame_index")
    private Integer frameIndex;

    /**
     * Timestamp when this frame was captured on the device.
     */
    @Field("captured_at")
    private Instant capturedAt;

    /**
     * Camera orientation at moment of capture.
     * pitch, yaw, roll from device sensors.
     * Stored as flexible JsonNode — varies by device type.
     */
    @Field("camera_orientation")
    private JsonNode cameraOrientation;

    /**
     * Camera exposure parameters at moment of capture.
     * iso, shutter_speed, aperture, white_balance.
     * Stored as flexible JsonNode — varies by device type.
     */
    @Field("exposure_params")
    private JsonNode exposureParams;

    /**
     * Whether this frame passed device-side quality check.
     * true  = passed validation on device
     * false = flagged but stored for backend decision
     */
    @Field("quality_flag")
    private Boolean qualityFlag;

    /**
     * Timestamp when this document was stored in MongoDB.
     * Set by storage-service at write time.
     * Used for audit trail and pipeline timing analysis.
     */
    @Field("stored_at")
    private Instant storedAt;
}