package com.ties.ingestion.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.List;

/**
 * CaptureBlock Model
 *
 * Represents a single capture block received from a mobile
 * acquisition device through the Apache Kafka pipeline.
 *
 * In the prototype configuration this data originates from
 * a Google Pixel 5 smartphone acting as the drone replacement.
 *
 * In the full drone configuration this data originates from
 * the drone edge computing subsystem after a waypoint capture
 * cycle completes.
 *
 * A capture block contains all frames captured at a single
 * observation position together with metadata describing
 * the capture context.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CaptureBlock {

    /**
     * Unique identifier for this capture block.
     * Generated by the acquisition device before transmission.
     * Format: DEVICE_ID-TIMESTAMP-SEQUENCE
     * Example: PIXEL5-001-1709123456789-001
     */
    @JsonProperty("block_identifier")
    private String blockIdentifier;

    /**
     * Unique identifier of the device that produced this block.
     * For prototype: PIXEL5-PROTOTYPE-001
     * For real drones: DRONE-001, DRONE-002, etc.
     */
    @JsonProperty("device_identifier")
    private String deviceIdentifier;

    /**
     * Unique identifier of the mission session this block
     * belongs to. Groups all capture blocks from one
     * mapping session together.
     */
    @JsonProperty("session_identifier")
    private String sessionIdentifier;

    /**
     * Timestamp when the first frame of this block was captured.
     * Stored as Unix timestamp in milliseconds.
     */
    @JsonProperty("capture_start_timestamp")
    private Instant captureStartTimestamp;

    /**
     * Timestamp when the last frame of this block was captured.
     * Difference between end and start represents capture window.
     * Should be approximately 5 seconds.
     */
    @JsonProperty("capture_end_timestamp")
    private Instant captureEndTimestamp;

    /**
     * Array of frame metadata objects.
     * Each entry describes one captured frame.
     * Expected count: 8 to 10 frames per block.
     */
    @JsonProperty("frames")
    private List<FrameMetadata> frames;

    /**
     * Human readable label describing where this capture
     * was taken. Provided by the user through the mobile app.
     * Example: "North corridor", "Room 3B", "Floor 2 entrance"
     */
    @JsonProperty("spatial_label")
    private String spatialLabel;

    /**
     * Quality confidence score assigned by the mobile app
     * after lightweight frame validation.
     * Range: 0.0 (unusable) to 1.0 (perfect quality)
     * Threshold for processing: above 0.5
     */
    @JsonProperty("quality_score")
    private Double qualityScore;

    /**
     * Checksum of the entire payload for integrity verification.
     * Generated by the device before transmission.
     * Backend validates this to detect transmission corruption.
     */
    @JsonProperty("checksum")
    private String checksum;

    /**
     * Current transmission status of this block.
     * Set by the device queue manager.
     * Values: PENDING, TRANSMITTING, ACKNOWLEDGED, FAILED
     */
    @JsonProperty("transmission_status")
    private String transmissionStatus;

    /**
     * Current lifecycle state of the acquisition session.
     * Values: SESSION_INITIATED, STABILIZATION_WAIT,
     * CAPTURE_WINDOW_ACTIVE, BLOCK_ASSEMBLY,
     * TRANSMISSION_PENDING, TRANSMITTING,
     * ACKNOWLEDGED, SESSION_COMPLETED
     */
    @JsonProperty("session_state")
    private String sessionState;
}